general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    color = rgb(11111b)
}

animations {
    enabled = false
}

input-field {
    monitor =
    size = 320, 48
    outline_thickness = 1
    dots_size = 0.2
    dots_spacing = 0.35
    outer_color = rgb(89b4fa)
    inner_color = rgb(181825)
    font_color = rgb(cdd6f4)
    fade_on_empty = false
    placeholder_text = Password
    fail_text = $FAIL ($ATTEMPTS)
    position = 0, 0
    halign = center
    valign = center
}
