# DMS generates and updates these files. Keep personal overrides below them.
source = ~/.config/hypr/dms/colors.conf
source = ~/.config/hypr/dms/layout.conf
source = ~/.config/hypr/dms/outputs.conf
source = ~/.config/hypr/dms/cursor.conf
source = ~/.config/hypr/dms/windowrules.conf

source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/autostart.conf

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
