source = ~/.config/themes/current/hyprlock.conf

background {
    monitor =
    color = $bg
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    outer_color = $accent
    inner_color = $field
    font_color = $fg
    placeholder_text = <i>Password...</i>
    fade_on_empty = false
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = $fg
    font_size = 48
    position = 0, 100
    halign = center
    valign = center
}
