#!/usr/bin/env bash
# Template rendering: @@KEY@@ placeholders substituted in a single sed pass.
#
# Deliberately not $KEY/${KEY} syntax: Hyprland configs already use their own
# $mod-style variables, so envsubst-style substitution would silently clobber
# those. @@KEY@@ can't collide with any Phase-1 consumer's native syntax.

template::_escape_sed_repl() {
	local v=$1
	v=${v//\\/\\\\}
	v=${v//&/\\&}
	v=${v//\//\\/}
	printf '%s' "$v"
}

# render_template <src> <dest> <values-array-name> [comment-prefix]
# comment-prefix defaults to "#"; jsonc callers should pass "//".
render_template() {
	local src=$1 dest=$2
	# Named _tmpl_values_ref, not "values" — a nameref colliding with a
	# same-named variable in the caller's scope trips bash's "circular name
	# reference" warning and silently fails to resolve.
	local -n _tmpl_values_ref=$3
	local comment=${4:-#}

	[[ -f $src ]] || log::die "render_template: no such template: ${src}"

	local -a sed_args=()
	local key escaped
	for key in "${!_tmpl_values_ref[@]}"; do
		escaped=$(template::_escape_sed_repl "${_tmpl_values_ref[$key]}")
		sed_args+=(-e "s/@@${key}@@/${escaped}/g")
	done

	local body
	body=$(mktemp)
	if [[ ${#sed_args[@]} -gt 0 ]]; then
		sed "${sed_args[@]}" "$src" >"$body"
	else
		cat "$src" >"$body"
	fi

	local header="${comment} Generated by dotfiles-hyprland. Do not edit directly; use preferences or a local override."
	mkdir -p "$(dirname "$dest")"
	# If the rendered file is an executable script, the shebang must stay on
	# line 1 (the kernel/shell won't recognize it otherwise) — the header
	# goes on line 2 instead in that case.
	if head -n1 "$body" | grep -q '^#!'; then
		{
			head -n1 "$body"
			printf '%s\n' "$header"
			tail -n +2 "$body"
		} >"$dest"
	else
		{
			printf '%s\n' "$header"
			cat "$body"
		} >"$dest"
	fi
	rm -f "$body"

	[[ -x $src ]] && chmod +x "$dest"

	if grep -qE '@@[A-Z][A-Z0-9_]*@@' "$dest"; then
		log::die "render_template: unresolved placeholder(s) in ${dest} (from ${src}): $(grep -oE '@@[A-Z][A-Z0-9_]*@@' "$dest" | sort -u | tr '\n' ' ')"
	fi
}
