#!/usr/bin/env bash
# Resolves the host profile and capability->package mapping, then builds the
# package plan. No mutation here — deploy.sh does the actual installing.

declare -gA HOST=()
declare -gA RESOLVED_PACKAGES=() # capability -> package name
declare -ga PLAN_MISSING_PACKAGES=()
declare -ga PLAN_PRESENT_PACKAGES=()
declare -g PLAN_HOST_NAME=""

# plan::_ensure_host_file <name>
# Auto-generates hosts/<name>.conf only when one doesn't already exist —
# never touches an existing file. Returns 0 if it created one, 1 if a file
# was already there. Scoped to install.sh's own first-run call site, not
# plan::resolve_host itself: dotctl (apply/diff/validate/profile
# plan|install) shares resolve_host, and a missing host file there should
# stay a loud error — it means something else is wrong on an
# already-set-up system, not a fresh machine that never had one.
plan::_ensure_host_file() {
	local name=$1
	local host_file="${DOTFILES_ROOT}/hosts/${name}.conf"
	[[ -f $host_file ]] && return 1

	if [[ ${OPT_DRY_RUN:-0} -eq 1 ]]; then
		log::info "plan::_ensure_host_file: [dry-run] would generate ${host_file}"
		return 1
	fi

	local host_type=desktop
	compgen -G '/sys/class/power_supply/BAT*' >/dev/null && host_type=laptop

	cat >"$host_file" <<EOF
# Host profile for this machine (hostname: ${name}), auto-generated by
# install.sh on first run since none existed. Review it — especially
# PRIMARY_OUTPUT and KEYBOARD_LAYOUT — once you can check \`hyprctl
# monitors\` from inside a running session; commit it once it's right.
HOST_TYPE=${host_type}
SESSION_MODE=tty
PRIMARY_OUTPUT=
INTERNAL_OUTPUT=
INTERNAL_ENABLED=0
KEYBOARD_LAYOUT=us
EOF
	log::info "plan::_ensure_host_file: generated ${host_file} (review PRIMARY_OUTPUT/KEYBOARD_LAYOUT)"
}

# plan::resolve_host <host-name>
# Precedence (lowest to highest): project preference defaults < installed
# tool-profile defaults < detected hardware facts < committed host profile
# < local untracked host override < --preference CLI flags. (Missing one
# HLD layer, "distribution adapter defaults" — a pre-existing gap, not
# related to profiles; see install/profile.sh's header.)
plan::resolve_host() {
	PLAN_HOST_NAME=$1
	local host_file="${DOTFILES_ROOT}/hosts/${PLAN_HOST_NAME}.conf"
	[[ -f $host_file ]] || log::die "plan::resolve_host: no such host profile: ${host_file}"

	local k
	local -A defaults=()
	kv_parse_file "${DOTFILES_ROOT}/preferences/defaults.conf" defaults
	for k in "${!defaults[@]}"; do HOST[$k]=${defaults[$k]}; done

	local -A profile_defaults=()
	profile::collect_preference_defaults profile_defaults
	for k in "${!profile_defaults[@]}"; do HOST[$k]=${profile_defaults[$k]}; done

	for k in "${!DETECTED[@]}"; do HOST[$k]=${DETECTED[$k]}; done

	local -A committed=()
	kv_parse_file "$host_file" committed
	for k in "${!committed[@]}"; do HOST[$k]=${committed[$k]}; done

	local local_override="${HOME}/.config/dotfiles/hosts/${PLAN_HOST_NAME}.local.conf"
	if [[ -f $local_override ]]; then
		local -A local_kv=()
		kv_parse_file "$local_override" local_kv
		for k in "${!local_kv[@]}"; do HOST[$k]=${local_kv[$k]}; done
	fi

	for k in "${!CLI_PREFERENCES[@]}"; do HOST[$k]=${CLI_PREFERENCES[$k]}; done

	log::info "plan::resolve_host: host=${PLAN_HOST_NAME} type=${HOST[HOST_TYPE]:-unknown} gpu=${HOST[GPU_VENDOR]:-unknown}/${HOST[GPU_MODE]:-unknown}"
}

plan::resolve_capabilities() {
	local caps_file="${DOTFILES_ROOT}/packages/capabilities.conf"
	local cap pkg
	while IFS= read -r cap; do
		[[ -z $cap || $cap == \#* ]] && continue
		pkg=$(adapter_resolve_capability "$cap") || log::die "plan::resolve_capabilities: capability unsupported by this adapter: ${cap}"
		RESOLVED_PACKAGES[$cap]=$pkg
	done <"$caps_file"
	log::info "plan::resolve_capabilities: resolved ${#RESOLVED_PACKAGES[@]} capabilities"
}

plan::build() {
	local cap pkg
	for cap in "${!RESOLVED_PACKAGES[@]}"; do
		pkg=${RESOLVED_PACKAGES[$cap]}
		if adapter_package_installed "$pkg"; then
			PLAN_PRESENT_PACKAGES+=("$pkg")
		else
			PLAN_MISSING_PACKAGES+=("$pkg")
		fi
	done
	log::info "plan::build: ${#PLAN_PRESENT_PACKAGES[@]} package(s) already present, ${#PLAN_MISSING_PACKAGES[@]} to install"
}

plan::print() {
	local p
	printf '\nInstall plan\n'
	printf '  host profile     : %s\n' "$PLAN_HOST_NAME"
	printf '  distro           : %s\n' "${HOST[DISTRO_ID]:-unknown}"
	printf '  gpu              : %s (%s)\n' "${HOST[GPU_VENDOR]:-unknown}" "${HOST[GPU_MODE]:-unknown}"
	printf '  packages present : %d\n' "${#PLAN_PRESENT_PACKAGES[@]}"
	printf '  packages to install (%d):\n' "${#PLAN_MISSING_PACKAGES[@]}"
	for p in "${PLAN_MISSING_PACKAGES[@]}"; do printf '    - %s\n' "$p"; done
	printf '\n'
}
