#!/usr/bin/env bash
# Renders templates into a scratch staging directory — never directly into
# $HOME. install/commit.sh promotes staged files into $HOME afterward.
# Everything under $STAGE_DIR/config/ mirrors $HOME/.config/; everything
# under $STAGE_DIR/home/ mirrors $HOME/ directly (for dotfiles like .bashrc
# that don't live under .config).

declare -g STAGE_DIR=""

stage::init() {
	STAGE_DIR=$(mktemp -d "${TMPDIR:-/tmp}/dotfiles-stage.XXXXXX")
	cleanup::register "$STAGE_DIR"
	log::info "stage::init: staging in ${STAGE_DIR}"
}

# stage::gpu_env_lines <format>  (format: envd | hypr | bash)
# GPU-specific variables are emitted only when GPU_VENDOR is nvidia — see
# HLD 11.4. Hybrid-offload variables are deliberately not built (see
# install/detect.sh); nothing is emitted for GPU_MODE=hybrid beyond this.
stage::gpu_env_lines() {
	local format=$1
	[[ ${HOST[GPU_VENDOR]:-} == nvidia ]] || return 0

	local -a vars=(LIBVA_DRIVER_NAME=nvidia __GLX_VENDOR_LIBRARY_NAME=nvidia NVD_BACKEND=direct)
	local kv
	for kv in "${vars[@]}"; do
		case $format in
		envd) printf '%s\n' "$kv" ;;
		hypr) printf 'env = %s,%s\n' "${kv%%=*}" "${kv#*=}" ;;
		bash) printf 'export %s\n' "$kv" ;;
		esac
	done
}

stage::generate_environment() {
	local -A values=() # no @@KEY@@ substitution needed yet; kept for header consistency

	render_template "${DOTFILES_ROOT}/config/environment/50-dotfiles.conf.tmpl" \
		"${STAGE_DIR}/config/environment.d/50-dotfiles.conf" values
	stage::gpu_env_lines envd >>"${STAGE_DIR}/config/environment.d/50-dotfiles.conf"

	render_template "${DOTFILES_ROOT}/config/environment/10-environment.conf.tmpl" \
		"${STAGE_DIR}/config/hypr/conf.d/10-environment.conf" values
	stage::gpu_env_lines hypr >>"${STAGE_DIR}/config/hypr/conf.d/10-environment.conf"

	render_template "${DOTFILES_ROOT}/config/environment/environment.bash.tmpl" \
		"${STAGE_DIR}/config/bash/environment.bash" values
	stage::gpu_env_lines bash >>"${STAGE_DIR}/config/bash/environment.bash"

	log::info "stage::generate_environment: rendered 3 environment file(s)"
}

# stage::generate_scripts — deploys static (non-templated) project scripts.
# Routed through render_template anyway (with an empty values map) so they
# get the same "generated by" header and drift-detection treatment as every
# other managed file.
stage::generate_scripts() {
	local -A values=()
	render_template "${DOTFILES_ROOT}/scripts/hypr-session" \
		"${STAGE_DIR}/home/.local/bin/hypr-session" values

	# dotctl needs its real DOTFILES_ROOT baked in — once staged to
	# ~/.local/bin/dotctl it can no longer derive it from its own path.
	local -A dotctl_values=([DOTFILES_ROOT_ABS]="$DOTFILES_ROOT")
	render_template "${DOTFILES_ROOT}/scripts/dotctl" \
		"${STAGE_DIR}/home/.local/bin/dotctl" dotctl_values

	log::info "stage::generate_scripts: rendered hypr-session, dotctl"
}

# stage::generate_applications — discovers applications/*/generate.sh and
# calls each module's <app>::generate. New app modules need no change here:
# dropping a new applications/<app>/generate.sh in is enough.
stage::generate_applications() {
	local script app
	for script in "${DOTFILES_ROOT}"/applications/*/generate.sh; do
		[[ -f $script ]] || continue
		app=$(basename "$(dirname "$script")")
		# shellcheck disable=SC1090  # genuinely dynamic: one per app module, not a fixed path
		source "$script"
		"${app}::generate"
	done
}

# stage::generate_systemd_units — renders config/systemd-user/*.tmpl into
# $HOME/.config/systemd/user/ (note the path split: the repo directory is
# named systemd-user for readability, but the runtime path is systemd/user).
stage::generate_systemd_units() {
	local -A values=([WALLPAPER_COLOR]="${HOST[WALLPAPER_COLOR]:-1a1b26}")
	local unit count=0
	for unit in "${DOTFILES_ROOT}"/config/systemd-user/*.tmpl; do
		[[ -f $unit ]] || continue
		render_template "$unit" \
			"${STAGE_DIR}/config/systemd/user/$(basename "${unit%.tmpl}")" values
		count=$((count + 1))
	done
	log::info "stage::generate_systemd_units: rendered ${count} unit(s)"
}
