color_theme = "Default"
theme_background = true
truecolor = true
vim_keys = true
rounded_corners = true
terminal_sync = true
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 2000
proc_sorting = "program"
proc_reversed = true
proc_mem_bytes = true
show_cpu_watts = true
check_temp = true
show_coretemp = true
show_battery = true
show_battery_watts = true
save_config_on_exit = false
